language: node_js
node_js:
  - 'node'
  - 'lts/*'
  - '10'
  - '10.15.3'
services:
  - elasticsearch
before_install:
  - curl -O https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-6.6.1.deb
  - sudo dpkg -i --force-confnew elasticsearch-6.6.1.deb
  - sudo service elasticsearch restart
before_script:
  - sleep 10
env:
  global:
    - NODE_ENV=test
    - SERVER_PROTOCOL=http
    - SERVER_HOSTNAME=localhost
    - SERVER_PORT=8888
    - ELASTICSEARCH_PROTOCOL=http
    - ELASTICSEARCH_HOSTNAME=localhost
    - ELASTICSEARCH_PORT=9200
    - ELASTICSEARCH_INDEX=test
    - PRIVATE_KEY="-----BEGIN PRIVATE KEY-----\n
      MIIJRQIBADANBgkqhkiG9w0BAQEFAASCCS8wggkrAgEAAoICAQDZC+RZ5kGJtN9W\n
      RBTrrsO/FQ4Zj39oAkRfVbSJd40XPis+pvxuwHghR7vM2ylNR1FV3r5RQXLHokhR\n
      xE5hlXsGjjqPjaTd5mzz8kcN4DLDEVhRqWD42rhLh5bQVJJV9kniTB1WwoTH1/7D\n
      YZJVEvLacSdLKxQyZYuRafmLovLRPs7yMaCoe2D/3GBgYsvedN3E4Mi+1GK5/SO1\n
      l84ldBfhSxU7qMYrW8My4VxCVq2jARZoMOVyvoDioj8wkFfuG3zEkARY75ki76Ds\n
      ViWp2jbbQVH7Hxyfk1frSssYkTrl9TueHzJuDnKJ8Xj6bfFeuSxVATLj1xw6Ncpz\n
      WhGxBoksUzbK4e8SVHrg4xixhD/i9ZWRR4VP5KzIP+t8rdrrI84B92YY7fVSqybH\n
      pfvBTefjaOqY59N267hFN1hkWzvESW4KNOy+XD/DuarlleX9/AF08KzpGqba09uK\n
      lPsAr0+m5g2/surkGq8CKAFpcAyBbHlDt18sn/N9B18RidlffmLQbBbiPMNV9VGr\n
      RW8N+Zph9U1GH/AOULG8MhgIsIgdDh9tRCnOgNts7+GjfYVEVxIJvRun1LgIl2Ev\n
      N0dpy6VJYXvpDfcMqDjFdjaw5CBXQAq9euSWd8RpMzaUvWO27JHqBt+mF/fDM+3K\n
      JrdF0xLOTbj8BiHTPdNrlN5QQjWvCwIDAQABAoICAQCujXPOIPGgL8hVdldk254t\n
      NF+sis0p9njKOwEAdRcRFDxvHJhy8XMrQKd2LuNedPaimopwirQmfQqwR7HJpQ/V\n
      y9iozn9CviftYHFoZWAtpOtkcVW9jRkeFSNi1EEDxRjSV+hYeAOVPM50jynCJYUN\n
      zGaPe0u45BWEkrfQZvHk+iAwg1zzYpY17yPLIGlYtKANz8FiRyhG76AiUL3HPUBf\n
      PaUL38XP5PJtHvS1nUPzjdJZZMmCqFa67UToZ41vvsduxWvZooeDozfGGdocaZQo\n
      bLXjwbehVjwkzHfdgB7gBYM2vVwvSosvCPYEYRr21PEkQ9yLg9n9rnjsoAkOV3VE\n
      p0fVpyaBNGD3q/fChlt073p5bC1ge7oVJTBxR0qOcC2+uc9hAERADTHEM/UzRF2F\n
      /JT2yI/rAEDD9OFivPlGdV0/NkonclfTldLNAL3TqSe5C7aUJGAHUkholTPBDWZy\n
      /zSGXPATbk9FvvzOghiup4QtwBhXKikRHtEiMYLkUSl63X8qUzcvtcVm5PvriRv9\n
      xJKfcqFBu93yoKOUMNT3Lgn9BCEFc7Wd+KkINP4hmXBu8ygMaqg20yuYnbX1ZSW/\n
      byOajwytiZuwsep+Pm0nYohvfhofVwM9nDaHiWfO6LdTFcTHPgQAZ/USpXp9EGPI\n
      CMr9X5T/r+0j9epj+sgl0QKCAQEA8F1vvi01USizLurcJQMq469A4C8IaOpqEwQX\n
      QdpjnWVgbzQjmMWYnGkXTunc5dEZoF0aFYXnqcvwzmS30Mkv+/xM+hfSjGG0VNZm\n
      kvbv+4S/uZJ/9xbSOzbEEgbtPgIEIAEHyJM3e74QZEuWUtItCkXdDyAW97aLmmkf\n
      ColwDeHFPH/uJACzfxt6lhcT7lochaNyiGjovlBj1C6wJ3Ppfq6ZsCNenHQo5WR6\n
      aMoKE1ThbgmLwiYjYgnvxzB4lLTDEDdXso/2xfS1cA1Wv8H4PjPcD/YV9oDy/k+m\n
      PIawrbfoHXWwkzalEKltR+mX+ZNLUIdtp0WboRLLCyWjf0+T/QKCAQEA5yonnEWM\n
      VOuEl+dQtCjMarDfHN0Us50PlLFuYTXXs/e8tHjlzSbJwi8JrIAB1U16UfnNhOB6\n
      8bQzHvOoCpafOltxMFVsNnQd4Sk6ylgczTpbxN/9ZLSl6tFji2S7JN+1ETiSGbKH\n
      r3O3sPz5cTintiq11ju6IH/gujUTSh8SyhcKoJ/rrqxV/IaBJXSXqaAARJQnZoaX\n
      XnMITwm4LhvipTRoiUL1f6bMcoObRaQa0lWceVoiHwBH8nc85+IU4UiIeD8DQOzg\n
      j5TxLGkYqdh1/h6jwjdXnLGb16T7lD8bmEylfqKoA6pJgxxJ21lvgkeBwyLbjqwJ\n
      vLBdsGHoVU1JpwKCAQEA4+UjQmPorldxdGV3bpxPOOr8DtJpHdhL1FXHm0dttVje\n
      EvGTYpDOflXhpI91Qmx76KD9TzTTjhjv6zBxW8K0/Syc625U0Yb9jIZvYJ5CsO2P\n
      PmpZa7O2hjAJvLHWlDkjIhj4AUMbkvaE4iMMlt/xllDhJCsfu6PXPwK2TK48kNzj\n
      vdXpuzby+Ovb0Zx16EKF0mtC93TIX1EnJZFSsUVkOBlhXDBczugPslcO/HW7EdMj\n
      ncntOZohaB3Vur0JRq0QWTqvqnx20/+NW306J7vIG2neF0ASWNKwEVEBY1etAjhh\n
      GjVwwlNIM8D//PPMhPQTr3mIDNWhlhmUa7A3EUkpHQKCAQEAp3Hxn1EBhcHUGfSE\n
      kPu8lsvn0ZCTHkf2sU6VFfVaehJJrrCkRSaDnxVTfJB8w3WL1TWNmWLBq7NMFG+K\n
      maDhVfRG2SwHZqpVunOTEl8g/cf4EXPuqLPyO1XRNXeR1/PzxLWlntejUYQQ2zNj\n
      vI+9bEcj0DsTZ9c5gahQgLBhe+GU4ST2I2DSKEmF4wvBkC1GBGcM40c6/j91FUuF\n
      DmFEm0aLMmI+UmkQTyLlplxo0VMSNRUFAk/BzfBxPcaWOVnBANkkEjODtn289N5r\n
      7xvM3HZ1SImt/OLqcBoh4hCUfI2Ik2JfMch313D2Tt1J2KTTafYl9ALKStO2Cb3h\n
      /WguoQKCAQEA0rqfgrv4Iyd7hv0IaIt4HFFR/iTXRpQsBrwKTFTD7k3k/t/8JNDU\n
      TwZ1YUkzvtRXvKIx0Xy9P0fHE+0VORWwJBV3OKkm1XBxzYpC4fPPXyrFCkRVW6ab\n
      z2JDJO5JWadMPWXoTdK/EXcnUe8XAjiaGnd8yYfK4eZlej/HRMQxDWAj/ZnsH6yS\n
      uI6PIfVvmnV6dEthsRN58I+7zhHGhG2TVJz2vkc9wuP2RKu800AwSsmFDLYJ4sfX\n
      Hu2MyqEPrdKIx8f4ShN8fLJNsV81wZV+rpzG8PXozR7J55a+KUeSaGm/z07GJPIr\n
      67zXmVHAunbTrDrm0g6d6M/eb/HUqYmhNw==\n
      -----END PRIVATE KEY-----"
